# app.yaml

runtime: nodejs18

instance_class: F2

env_variables:
  # Add any necessary environment variables here
  # For example, if you have other configurations, add them below
  # SUPPLIER_ID: 'S068'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /styles.css
    static_files: public/styles.css
    upload: public/styles.css

  - url: /sample_product_prices.csv
    static_files: public/sample_product_prices.csv
    upload: public/sample_product_prices.csv

  - url: /static
    static_dir: public

  - url: /.*
    script: auto
